src/Modules/SimplCommerce.Module.Reviews/Areas/Reviews/ViewModels/Reply.cs
using System;

namespace SimplCommerce.Module.Reviews.Areas.Reviews.ViewModels
{
    public class Reply
    {
        public string Comment { get; set; }

        public string ReplierName { get; set; }

        public DateTimeOffset CreatedOn { get; set; }
    }
}

src/Modules/SimplCommerce.Module.Reviews/Areas/Reviews/ViewModels/ReplyForm.cs
using System.ComponentModel.DataAnnotations;

namespace SimplCommerce.Module.Reviews.Areas.Reviews.ViewModels
{
    public class ReplyForm
    {
        [Required(ErrorMessage = "The {0} field is required.")]
        public string Comment { get; set; }

        public string ReplierName { get; set; }

        public long ReviewId { get; set; }
    }
}

src/Modules/SimplCommerce.Module.Reviews/Models/Reply.cs
using System;
using System.ComponentModel.DataAnnotations;
using SimplCommerce.Infrastructure.Models;
using SimplCommerce.Module.Core.Models;

namespace SimplCommerce.Module.Reviews.Models
{
    public class Reply : EntityBase
    {
        public Reply()
        {
            Status = ReplyStatus.Pending;
            CreatedOn = DateTimeOffset.Now;
        }

        public long ReviewId { get; set; }

        public Review Review { get; set; }

        public long UserId { get; set; }

        public User User { get; set; }

        public string Comment { get; set; }

        [StringLength(450)]
        public string ReplierName { get; set; }

        public ReplyStatus Status { get; set; }

        public DateTimeOffset CreatedOn { get; set; }
    }
}

src/Modules/SimplCommerce.Module.Reviews/Areas/Reviews/Controllers/ReplyController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimplCommerce.Infrastructure.Data;
using SimplCommerce.Module.Core.Extensions;
using SimplCommerce.Module.Reviews.Areas.Reviews.ViewModels;

namespace SimplCommerce.Module.Reviews.Areas.Reviews.Controllers
{
    [Area("Reviews")]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class ReplyController : Controller
    {
        private readonly IRepository<Models.Reply> _replyRepository;
        private readonly IWorkContext _workContext;

        public ReplyController(IRepository<Models.Reply> replyRepository, IWorkContext workContext)
        {
            _replyRepository = replyRepository;
            _workContext = workContext;
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddReply(ReplyForm model)
        {
            if (ModelState.IsValid)
            {
                var user = await _workContext.GetCurrentUser();
                model.ReplierName = user.FullName;

                var reply = new Models.Reply
                {
                    ReviewId = model.ReviewId,
                    UserId = user.Id,
                    Comment = model.Comment,
                    ReplierName = user.FullName
                };

                _replyRepository.Add(reply);
                _replyRepository.SaveChanges();

                return PartialView("_ReplyFormSuccess", model);
            }

            return PartialView("_ReplyForm", model);
        }
    }
}

src/Modules/SimplCommerce.Module.Reviews/Areas/Reviews/Views/Reply/_ReplyForm.cshtml
@using SimplCommerce.Module.Core.Models
@using SimplCommerce.Module.Core.Extensions

@model SimplCommerce.Module.Reviews.Areas.Reviews.ViewModels.ReplyForm

@inject IWorkContext WorkContext
@inject SignInManager<User> SignInManager


@if (SignInManager.IsSignedIn(User))
{
    <form class="form-add-review-reply" asp-area="Reviews" asp-controller="Reply" asp-action="AddReply" method="post" role="form">
        <input asp-for="ReviewId" type="hidden" />
        <div class="form-group">
            <textarea asp-for="Comment" rows="3" placeholder="@Localizer["Your reply"]" maxlength="300" class="form-control"></textarea>
            <span asp-validation-for="Comment" class="text-danger"></span>
        </div>
        <div class="form-group text-right">
             <button class="btn btn-secondary btn-submit-review-reply" type="submit">@Localizer["Submit reply"]</button>
        </div>
    </form>
}
else
{
    var localizedTextParts = Localizer["Please <a>login</a> or <a>register</a> to submit your reply."].GetTextPartsFunction("<a>", "</a>");
    <p>@localizedTextParts(0)<a href="~/login?ReturnUrl=@Context.Request.Path">@localizedTextParts(1)</a>@localizedTextParts(2)<a href="~/register?ReturnUrl=@Context.Request.Path">@localizedTextParts(3)</a>@localizedTextParts(4)</p>
}

src/Modules/SimplCommerce.Module.Reviews/Areas/Reviews/Views/Reply/_ReplyFormSuccess.cshtml
@model SimplCommerce.Module.Reviews.Areas.Reviews.ViewModels.ReplyForm

<div class="alert alert-success" role="alert">
    <h4>
        @Localizer["Thank you {0} for your reply", Model.ReplierName]
    </h4>

    <p>@Localizer["Your reply will be shown within the next 24h."]</p>
</div>