src/Modules/SimplCommerce.Module.Orders/Areas/Orders/Controllers/CheckoutController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using SimplCommerce.Infrastructure.Data;
using SimplCommerce.Module.Core.Extensions;
using SimplCommerce.Module.Core.Models;
using SimplCommerce.Module.Orders.Areas.Orders.ViewModels;
using SimplCommerce.Module.Orders.Services;
using SimplCommerce.Module.ShippingPrices.Services;
using SimplCommerce.Module.ShoppingCart.Models;
using SimplCommerce.Module.ShoppingCart.Services;

namespace SimplCommerce.Module.Orders.Areas.Orders.Controllers
{
    [Area("Orders")]
    [Route("checkout")]
    [Authorize]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class CheckoutController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IRepositoryWithTypedId<Country, string> _countryRepository;
        private readonly IRepository<StateOrProvince> _stateOrProvinceRepository;
        private readonly IRepository<UserAddress> _userAddressRepository;
        private readonly IShippingPriceService _shippingPriceService;
        private readonly ICartService _cartService;
        private readonly IWorkContext _workContext;
        private readonly IRepository<Cart> _cartRepository;

        public CheckoutController(
            IRepository<StateOrProvince> stateOrProvinceRepository,
            IRepositoryWithTypedId<Country, string> countryRepository,
            IRepository<UserAddress> userAddressRepository,
            IShippingPriceService shippingPriceService,
            IOrderService orderService,
            ICartService cartService,
            IWorkContext workContext,
            IRepository<Cart> cartRepository)
        {
            _stateOrProvinceRepository = stateOrProvinceRepository;
            _countryRepository = countryRepository;
            _userAddressRepository = userAddressRepository;
            _shippingPriceService = shippingPriceService;
            _orderService = orderService;
            _cartService = cartService;
            _workContext = workContext;
            _cartRepository = cartRepository;
        }

        [HttpGet("shipping")]
        public async Task<IActionResult> Shipping()
        {
            var currentUser = await _workContext.GetCurrentUser();
            var cart = await _cartService.GetActiveCartDetails(currentUser.Id);
            if(cart == null || !cart.Items.Any())
            {
                return Redirect("~/");
            }

            var model = new DeliveryInformationVm();

            PopulateShippingForm(model, currentUser);

            return View(model);
        }

        [HttpPost("shipping")]
        public async Task<IActionResult> Shipping(DeliveryInformationVm model)
        {
            var currentUser = await _workContext.GetCurrentUser();
            // TODO Handle error messages
            if ((!model.NewAddressForm.IsValid() && model.ShippingAddressId == 0) ||
                (!model.NewBillingAddressForm.IsValid() && !model.UseShippingAddressAsBillingAddress && model.BillingAddressId == 0))
            {
                PopulateShippingForm(model, currentUser);
                return View(model);
            }

            var cart = await _cartService.GetActiveCart(currentUser.Id);

            if (cart == null)
            {
                throw new ApplicationException($"Cart of user {currentUser.Id} cannot be found");
            }

            cart.ShippingData = JsonConvert.SerializeObject(model);
            await _cartRepository.SaveChangesAsync();
            return Redirect("~/checkout/payment");
        }

        [HttpPost("update-tax-and-shipping-prices")]
        public async Task<IActionResult> UpdateTaxAndShippingPrices([FromBody] TaxAndShippingPriceRequestVm model)
        {
            var currentUser = await _workContext.GetCurrentUser();
            var cart = await _cartService.GetActiveCart(currentUser.Id);
            var orderTaxAndShippingPrice = await _orderService.UpdateTaxAndShippingPrices(cart.Id, model);

            return Ok(orderTaxAndShippingPrice);
        }

        [HttpGet("success")]
        public IActionResult Success(long orderId)
        {
            return View(orderId);
        }

        [HttpGet("error")]
        public IActionResult Error(long orderId)
        {
            return View(orderId);
        }

        [HttpPost("cancel")]
        public async Task<IActionResult> Cancel()
        {
            var currentUser = await _workContext.GetCurrentUser();
            var cart = await _cartService.GetActiveCart(currentUser.Id);
            if(cart != null && cart.LockedOnCheckout)
            {
                cart.LockedOnCheckout = false;
                await _cartRepository.SaveChangesAsync();
            }

            return Redirect("~/");
        }

        private void PopulateShippingForm(DeliveryInformationVm model, User currentUser)
        {
            model.ExistingShippingAddresses = _userAddressRepository
                .Query()
                .Where(x => (x.AddressType == AddressType.Shipping) && (x.UserId == currentUser.Id))
                .Select(x => new ShippingAddressVm
                {
                    UserAddressId = x.Id,
                    ContactName = x.Address.ContactName,
                    Phone = x.Address.Phone,
                    AddressLine1 = x.Address.AddressLine1,
                    CityName = x.Address.City,
                    ZipCode = x.Address.ZipCode,
                    DistrictName = x.Address.District.Name,
                    StateOrProvinceName = x.Address.StateOrProvince.Name,
                    CountryName = x.Address.Country.Name,
                    IsCityEnabled = x.Address.Country.IsCityEnabled,
                    IsZipCodeEnabled = x.Address.Country.IsZipCodeEnabled,
                    IsDistrictEnabled = x.Address.Country.IsDistrictEnabled
                }).ToList();

            model.ShippingAddressId = currentUser.DefaultShippingAddressId ?? 0;

            model.UseShippingAddressAsBillingAddress = true;

            model.NewAddressForm.ShipableContries = _countryRepository.Query()
                .Where(x => x.IsShippingEnabled)
                .OrderBy(x => x.Name)
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToList();

            if (model.NewAddressForm.ShipableContries.Count == 1)
            {
                var onlyShipableCountryId = model.NewAddressForm.ShipableContries.First().Value;

                model.NewAddressForm.StateOrProvinces = _stateOrProvinceRepository
                .Query()
                .Where(x => x.CountryId == onlyShipableCountryId)
                .OrderBy(x => x.Name)
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToList();
            }
        }
    }
}

src/Modules/SimplCommerce.Module.Orders/Areas/Orders/Views/Checkout/Shipping.cshtml
@model SimplCommerce.Module.Orders.Areas.Orders.ViewModels.DeliveryInformationVm

@{
    ViewBag.Title = "Shipping Information";
}

<div class="row">
    <div class="col-md-8">
        <form asp-area="Orders" asp-controller="Checkout" asp-action="Shipping" method="POST" id="checkout-delivery-address">
            <h3>@Localizer["Shipping address"]</h3>
            @foreach (var address in Model.ExistingShippingAddresses)
            {
                <div class="radio">
                    <label>
                        <input type="radio" name="ShippingAddressId" value="@address.UserAddressId" checked="@(Model.ShippingAddressId == address.UserAddressId ? "checked" : null)">
                        <strong>@address.ContactName </strong><br />
                        @address.AddressLine1 <br />
                        @address.AddressLine2 <br />
                        Phone: @address.Phone
                    </label>
                </div>
            }
            <div class="radio">
                <label>
                    <input type="radio" name="ShippingAddressId" checked="@(Model.ShippingAddressId == 0 ? "checked" : null)" value="0" />
                    @Localizer["Add another address"]
                </label>
            </div>
            <div class="create-shipping-address collapse">
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">@Localizer["Contact name"]</label>
                    <div class="col-sm-8">
                        <input asp-for="NewAddressForm.ContactName" type="text" class="form-control">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">@Localizer["Country"]</label>
                    <div class="col-sm-8">
                        <select asp-for="NewAddressForm.CountryId" asp-items="Model.NewAddressForm.ShipableContries" class="form-control">
                            <option value="">@Localizer["Choose one"]</option>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">@Localizer["State or Province"]</label>
                    <div class="col-sm-8">
                        <select asp-for="NewAddressForm.StateOrProvinceId" asp-items="Model.NewAddressForm.StateOrProvinces" class="form-control">
                            <option value="">@Localizer["Choose one"]</option>
                        </select>
                    </div>
                </div>

                <div id="form-group-district" class="form-group row">
                    <label class="col-sm-4 col-form-label">@Localizer["District"]</label>
                    <div class="col-sm-8">
                        <select asp-for="NewAddressForm.DistrictId" asp-items="Model.NewAddressForm.Districts" class="form-control">
                            <option value=""></option>
                        </select>
                    </div>
                </div>

                <div id="form-group-city" class="form-group row">
                    <label class="col-sm-4 col-form-label">@Localizer["City"]</label>
                    <div class="col-sm-8">
                        <input asp-for="NewAddressForm.City" type="text" class="form-control">
                    </div>
                </div>

                <div id="form-group-postalcode" class="form-group row">
                    <label class="col-sm-4 col-form-label">@Localizer["Postal Code"]</label>
                    <div class="col-sm-8">
                        <input asp-for="NewAddressForm.ZipCode" type="text" class="form-control">
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">@Localizer["Address"]</label>
                    <div class="col-sm-8">
                        <input asp-for="NewAddressForm.AddressLine1" type="text" class="form-control">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">@Localizer["Phone"]</label>
                    <div class="col-sm-8">
                        <input asp-for="NewAddressForm.Phone" type="text" class="form-control">
                    </div>
                </div>
            </div>
            <h3>@Localizer["Shipping methods"]</h3>
            <div id="shippingMethods">
                <p>Please choose your shipping address</p>
            </div>

            <div>
                <h3>@Localizer["Billing Address"]</h3>
                <label>
                    <input type="checkbox" name="UseShippingAddressAsBillingAddress" checked="@(Model.UseShippingAddressAsBillingAddress ? "checked" : null)" value="true" />
                    @Localizer["Use Selected Shipping Address As Billing Address"]
                </label>
            </div>
            <div class="change-billing-address collapse">
                @foreach (var address in Model.ExistingShippingAddresses)
                {
                    <div class="radio">
                        <label>
                            <input type="radio" name="BillingAddressId" value="@address.UserAddressId" checked="@(Model.BillingAddressId == address.UserAddressId ? "checked" : null)">
                            <strong>@address.ContactName </strong><br />
                            @address.AddressLine1 <br />
                            @address.AddressLine2 <br />
                            Phone: @address.Phone
                        </label>
                    </div>
                }
                <div class="radio">
                    <label>
                        <input type="radio" name="BillingAddressId" checked="@(Model.BillingAddressId == 0 ? "checked" : null)" value="0" />
                        @Localizer["Add another address"]
                    </label>
                </div>
                <div class="create-billing-address collapse">
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">@Localizer["Contact name"]</label>
                        <div class="col-sm-8">
                            <input asp-for="NewBillingAddressForm.ContactName" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">@Localizer["Country"]</label>
                        <div class="col-sm-8">
                            <select asp-for="NewBillingAddressForm.CountryId" asp-items="Model.NewAddressForm.ShipableContries" class="form-control">
                                <option value="">@Localizer["Choose one"]</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">@Localizer["State or Province"]</label>
                        <div class="col-sm-8">
                            <select asp-for="NewBillingAddressForm.StateOrProvinceId" asp-items="Model.NewAddressForm.StateOrProvinces" class="form-control">
                                <option value="">@Localizer["Choose one"]</option>
                            </select>
                        </div>
                    </div>

                    <div id="form-group-district" class="form-group row">
                        <label class="col-sm-4 col-form-label">@Localizer["District"]</label>
                        <div class="col-sm-8">
                            <select asp-for="NewBillingAddressForm.DistrictId" asp-items="Model.NewAddressForm.Districts" class="form-control">
                                <option value=""></option>
                            </select>
                        </div>
                    </div>

                    <div id="form-group-city" class="form-group row">
                        <label class="col-sm-4 col-form-label">@Localizer["City"]</label>
                        <div class="col-sm-8">
                            <input asp-for="NewBillingAddressForm.City" type="text" class="form-control">
                        </div>
                    </div>

                    <div id="form-group-postalcode" class="form-group row">
                        <label class="col-sm-4 col-form-label">@Localizer["Postal Code"]</label>
                        <div class="col-sm-8">
                            <input asp-for="NewBillingAddressForm.ZipCode" type="text" class="form-control">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">@Localizer["Address"]</label>
                        <div class="col-sm-8">
                            <input asp-for="NewBillingAddressForm.AddressLine1" type="text" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">@Localizer["Phone"]</label>
                        <div class="col-sm-8">
                            <input asp-for="NewBillingAddressForm.Phone" type="text" class="form-control">
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="text-right">
                    <button type="submit" class="btn btn-order" disabled>@Localizer["Payment"]</button>
                </div>
            </div>
        </form>
        <div class="text-right">
            <form asp-area="Order" asp-controller="Checkout" asp-action="Cancel" method="post" id="logoutForm" class="">
                <button type="submit" class="btn btn-secondary active ">@Localizer["Cancel Order"]</button>
            </form>
        </div>
    </div>
    <div class="col-md-4">
        @await Component.InvokeAsync("OrderSummary")
    </div>
</div>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
    <script simpl-append-version="true" src="~/_content/SimplCommerce.Module.Orders/checkout.js"></script>
}

src/Modules/SimplCommerce.Module.Orders/Areas/Orders/Views/Checkout/Success.cshtml
@model long

@{
    ViewBag.Title = "Result";
    var localizedTextParts = Localizer["We received <a>your order</a>. Thank you!"].GetTextPartsFunction("<a>", "</a>");
}

<h2>@Localizer["Congratulation!"]</h2>
<p>@localizedTextParts(0)<a href="~/user/orders/@Model">@localizedTextParts(1)</a>@localizedTextParts(2)</p>